### ISSUE TITLE
Rust integration tests for Manta runtime

### ISSUE THREAD

**Issue by ghzlatarev** [Manta-Network/Manta#1070]
Similar to the Calamari integration tests.

**Comment by Dengjianping** [comment]
I would recommend moving integration tests out of calamari, to become a separated crates, then using features to control which runtime to be tested, like 
```rust
#[cfg(feature = "calamari-runtime")]
type Runtime = calamari_runtime::Runtime;

#[cfg(feature = "manta-runtime")]
type Runtime = manta_runtime::Runtime
```
