### ISSUE TITLE
Create New zkSBT MintTypes Without a Runtime Upgrade

### ISSUE THREAD

**Issue by ferrell-code** [Manta-Network/Manta#1081]
Right now to add new mint type we need update this enum: https://github.com/Manta-Network/Manta/blob/ceb9e46cd53b77eb914ba6c17452fc238bc3a28f/pallets/manta-sbt/src/lib.rs#L134

We should add an `MintType` registry to add new zkSBT `MintTypes` onchain dynamically. Migrating existing storage will be necessary, I think doing it lazily using `on_idle` hook is best way to go due to number of existing zkSBT mints already completed

**Comment by Dengjianping** [comment]
Not sure it's a good way to do migration during block production.
```rust
/// This will be run when the block is being finalized (before `on_finalize`).
/// Implement to have something happen using the remaining weight.
/// Will not fire if the remaining weight is 0.
/// Return the weight used, the hook will subtract it from current weight used
/// and pass the result to the next `on_idle` hook if it exists.
fn on_idle(
    _n: BlockNumber,
    _remaining_weight: crate::weights::Weight,
) -> crate::weights::Weight {
    0
}
```

And I check the count of `EvmAddressAllowlist` storage items, it's over 39K, but we have 500ms block proposal time, not sure it can be done within 500ms.

There's an interesting postmortem from altair:
https://medium.com/altair-network/altair-runtime-upgrade-2-a-post-mortem-618d8c3b12d8

**Comment by ferrell-code** [comment]
We would migrate over many blocks using on_idle.

 I believe that if a mint is not active than the relevant storage items can be migrated over the course of a few days as they are not accessed by a valid tx in runtime code. Of course this will need to be tested.
