### ISSUE TITLE
pallet-assets error in manta-pc runtime

### ISSUE THREAD

**Issue by ghzlatarev** [Manta-Network/Manta#115]
### Minimal example:

1. Pull and build https://github.com/ghzlatarev/pallet-assets-integration-error
    The only changes are the integration of pallet-assets in:
    - ``Cargo.toml``
    -  https://github.com/ghzlatarev/pallet-assets-integration-error/blob/master/runtime/src/lib.rs#L292
    -  https://github.com/ghzlatarev/pallet-assets-integration-error/blob/master/runtime/src/lib.rs#L331
2. Run ``./target/release/node-template --dev --tmp``
3. Go to ``Network->Assets->Create Asset`` in the front end and try to create an asset
4. The error that should be reproduced is:

```
submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1002: Verification Error: Runtime error: Execution failed: ApiError(FailedToConvertParameter { function: "validate_transaction", parameter: "tx", error: Error { cause: Some(Error { cause: Some(Error { cause: None, desc: "Not enough data to fill buffer" }), desc: "Could not decode `Call::create.2`" }), desc: "Could not decode `Call::Assets.0`" } }): RuntimeApi, Execution failed: ApiError, FailedToConvertParameter { function: \"validate_transaction\", parameter: \"tx\", error: Error { cause: Some, Error { cause: Some, Error { cause: None, desc: \"Not enough data to fill buffer\" }, desc: \"Could not…
```
Please take note of the follolwing line `` type Balance = u128; // u64 no errors `` 
Not sure why ``u64`` fixes the issue, that's the real question here.

### Not so minimal example:

1. Pull and build ``manta-pc`` on branch ``add-calamari-runtime`` = https://github.com/Manta-Network/Manta/tree/add-calamari-runtime 
    This version of the runtime uses the following dependencies:
    polkadot: branch = "release-v0.9.7"
    substrate: branch = "polkadot-v0.9.7"
    cumulus: branch = "polkadot-v0.9.7"

2. Pull and build ``polkadot`` on branch ``release-v0.9.7`` = https://github.com/paritytech/polkadot/tree/release-v0.9.7 
    2.1. cherry pick this to avoid rococo-native only error in manta-pc-launch  tool -> 
           https://github.com/paritytech/polkadot/commit/b66483bc368812237469e1ff83dfea590fe8050f
3. Pull and build ``manta-pc-launch`` = https://github.com/Manta-Network/manta-pc-launch
     https://github.com/Manta-Network/manta-pc-launch/blob/master/config.json we set up a ``rococo-local`` relay chain and two ``manta-pc`` parachains.

Run ``manta-pc-launch`` and once the testnet is running, go to the one of the parachain nodes from the front end.

Simply try to create a new asset from Network->Assets view.

The error that should be reproduced is the following:

```
1002: Verification Error: Runtime error: Execution failed: ApiError(FailedToConvertParameter { function: "validate_transaction", parameter: "tx", error: Error { cause: Some(Error { cause: Some(Error { cause: None, desc: "Could not decode `Call`, variant doesn't exist" }), desc: "Could not decode `Call::batch_all.0`" }), desc: "Could not decode `Call::Utility.0`" } }): RuntimeApi, Execution failed: ApiError, FailedToConvertParameter { function: \"validate_transaction\", parameter: \"tx\", error: Error { cause: Some, Error { cause: Some, Error { cause: None, desc: \"Could not decode `Call`, variant doesn't exist\" }, d…
```

Types in Polkadot.js Settings->Developer are the following:

```
{
  "Address": "MultiAddress",
  "LookupSource": "MultiAddress",
  "AssetDetails": {
    "owner": "AccountId",
    "issuer": "AccountId",
    "admin": "AccountId",
    "freezer": "AccountId",
    "supply": "Balance",
    "deposit": "Balance",
    "min_balance": "Balance",
    "is_sufficient": "bool",
    "accounts": "u32",
    "sufficient": "u32",
    "approvals": "u32",
    "is_frozen": "bool"
  },
  "AssetBalance": {
    "balance": "Balance",
    "is_frozen": "bool",
    "sufficient": "bool",
    "extra": ""
  },
  "AssetMetadata": {
    "deposit": "Balance",
    "name": "Vec<u8>",
    "symbol": "Vec<u8>",
    "decimals": "u8",
    "is_frozen": "bool"
  },
  "DebitFlags": {
    "keep_alive": "bool",
    "best_effort": "bool"
  },
  "TransferFlags": {
    "keep_alive": "bool",
    "best_effort": "bool",
    "burn_dust": "bool"
  },
  "DestroyWitness": {
    "accounts": "u32",
    "sufficients": "u32",
    "approvals": "u32"
  },
  "Approval": {
    "amount": "Balance",
    "deposit": "DepositBalance"
  }
}
```

The integration is practically the same as in here -> https://github.com/paritytech/substrate/blob/master/bin/node/runtime/src/lib.rs

**Comment by Dengjianping** [comment]
Second quesiton:
When I add `BuyExecution` order to xcm, and this xcm is sent to target chain, but target chain will report `TooExepense`? 
What does extractly that mean?

**Comment by shawntabrizi** [comment]
Just wanted to say thanks for a minimal example!

**Comment by shawntabrizi** [comment]
@Dengjianping 

```
	/// The assets given to purchase weight is are insufficient for the weight desired.
	TooExpensive,
	
```

I think you need to put more assets into the XCM, since the error says you are not paying enough fee for the weight you want

**Comment by xialovexia** [comment]
Third question: 
When multiple accounts' crowdloan have an equal amount, who wins the auction last?

**Comment by shawntabrizi** [comment]
To solve your first question, I figured it out!

you need to specify a custom type for the `Assets::Balances` type, since the UI expects `u64` and you want to use `u128`.

To do this, just add:

```
"TAssetsBalance": "u128"
```

to your JSON types

**Comment by shawntabrizi** [comment]
> Third question:
> When multiple accounts' crowdloan have an equal amount, who wins the auction last?

It depends on the ending period and selecting a random winner!

Although if we are talking about 2 users having the EXACT same bid, the first one will stay the winner until the next guy gets even .00000000001 more KSM

**Comment by ghzlatarev** [comment]
> To solve your first question, I figured it out!
> 
> you need to specify a custom type for the `Assets::Balances` type, since the UI expects `u64` and you want to use `u128`.
> 
> To do this, just add:
> 
> ```
> "TAssetsBalance": "u128"
> ```
> 
> to your JSON types

Hey Shawn, tested it and it's not working on my side for some strange reason.
The only inconsistency with what you did is that my Polkadot-JS front-end shows ``apps v0.94.2-58`` and yours was ``apps v0.94.2-55`` but that can't be a problem , can it ?

**Comment by ghzlatarev** [comment]
> > To solve your first question, I figured it out!
> > you need to specify a custom type for the `Assets::Balances` type, since the UI expects `u64` and you want to use `u128`.
> > To do this, just add:
> > ```
> > "TAssetsBalance": "u128"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to your JSON types
> 
> Hey Shawn, tested it and it's not working on my side for some strange reason.
> The only inconsistency with what you did is that my Polkadot-JS front-end shows `apps v0.94.2-58` and yours was `apps v0.94.2-55` but that can't be a problem , can it ?

Oops false alarm. 
Was using `` TAssetsBalance `` plural instead of `` TAssetBalance `` singular.
