### ISSUE TITLE
Need to unStake all LPToken from farming

### ISSUE THREAD

**Issue by DanielZhangReal** [Manta-Network/Manta#1172]
**Issue Description:**

we have a Farming module, which needs to stake the user's LPToken, and then can get token rewards. When I stake LPTokens to farming, I cannot remove all LPTokens. 

For example, **if I stake 100 LPTokens in Farming, I will fail to withdraw 100**. The screenshot of the specific error message is as follows:

Related code:

``` typescript
const args = [
  pid,
  amountToWithdraw?.quotient.toString() ?? '0',
]
const extrinsic = [
  api.tx.farming.withdraw(...args),
  api.tx.farming.withdrawClaim(pid),
]
```

Same error in: `api.tx.farming.claim(pid)`

**Comment by zqhxuyuan** [comment]
fix by use `AllowDeath` strategy when transfer tokens on `currencies` implements.
