### ISSUE TITLE
Sending private transaction

### ISSUE THREAD

**Issue by klynkc** [Manta-Network/Manta#1285]
Manta network provides users with public web socket so that they can subscribe any pending transaction.
Is there any way to send transactions that user can not listen them?

**Comment by Dengjianping** [comment]
I'm not sure what you really mean.
Generally, users can only listen to their own transactions. But there's transaction pool which contains pending transactions, you can find related api here: https://polkadot.js.org/docs/kusama/rpc#pendingextrinsics-vecextrinsic

**Comment by klynkc** [comment]
For examples, I can subcribe pending transaction from websocket, however, for specific cases, I can not find them on it. I think they are using other ways to send the transaction, not the rpc

**Comment by Dengjianping** [comment]
As far as I know, any signed or unsigned extrinsic will be submitted finally by this rpc method `author_submitExtrinsic`:
![image](https://github.com/Manta-Network/Manta/assets/1914204/357829e6-783a-47ef-bf0c-c0b493518c40)

But I'm not sure parity has implemented this already or not:
https://paritytech.github.io/json-rpc-interface-spec/api/transaction.html

**Comment by klynkc** [comment]
Can it be applied for Manta Pacific?

**Comment by klynkc** [comment]
Is Manta Pacific based on Polygon zkEVM or Polkadot?

**Comment by Dengjianping** [comment]
> Is Manta Pacific based on Polygon zkEVM or Polkadot?

Based on polygon zkevm.
