### ISSUE TITLE
Manta Wallet "Block Sync Failed"

### ISSUE THREAD

**Issue by 4u2hear3000** [Manta-Network/Manta#1289]
![KMA Calamari Manta](https://github.com/Manta-Network/Manta/assets/135171640/8b38b511-3961-47dd-8692-a053e131a842)

Using Manta Wallet Version 0.0.25 - it is failing to Sync, any suggestions?

**Comment by Dengjianping** [comment]
I'm not 100% sure what the real problem is, but it seems a network issue.
Can you show me the console of your browser when you refresh this page?

**Comment by Dengjianping** [comment]
I'm going to close it. If you have this issue again, please reopen it.
