### ISSUE TITLE
Is there a bug bounty? 

### ISSUE THREAD

**Issue by hasnali456578** [Manta-Network/Manta#1305]
Is there a bug bounty?  I found a security vulnerability. Is there a reward for this?

**Comment by Dengjianping** [comment]
We're planning the bug bounty program, but not ready for community yet. We will value how vulnerable that issue is, then decide how to reward you. Can you send me an email about that issue? My email: `jamie.deng@manta.network`.

**Comment by Dengjianping** [comment]
I'm going to close this issue, please send me an email! Move our conversation there.

**Comment by hasnali456578** [comment]
I sent you an e-mail, could you please check it?

**Comment by hasnali456578** [comment]
Were you able to view the e-mail message?
