### ISSUE TITLE
Manta brigde Pacific to Atlantic failed

### ISSUE THREAD

**Issue by hoanngothanh** [Manta-Network/Manta#1308]
Hello Manta

Could someone help me on Manta bridge from Pacific to Alantic ?

I bridged 1k2 MANTA but seem have bug on website lead to it can not open dialog to do next step (free fee on Moonbeam etc)

and I lost Manta on Metamask but not receive MANTA on Manta Atlantic (Manta wallet)

I made 2 tx but seem both failed 

https://pacific-explorer.manta.network/tx/0x1d2ce1df784164e51c7f85760327e0c5aac661f8be9e642282da22166e5c22fb

https://pacific-explorer.manta.network/tx/0x7a325f791e06fd356ef973a60bc7a758359b0ca544ea4b4f710283bb808ad4c6

**Comment by jasonintju** [comment]
Hi, 
Your $MANTA token has successfully transferred from Manta Pacific to Moonbeam, the token is on Moonbeam network now. https://moonbeam.moonscan.io/token/0xffffffff7d3875460d4509eb8d0362c611b4e841?a=0xE1b90761725E6e89502D23d9ef4632C6F0a84042

For now, you can withdraw some GLMR from CEX to your erc20 address to be gas fee on Moonbeam network, then you can transfer $MANTA from Moonbeam to Atlantic in our website. https://app.manta.network/manta/bridge

Thank you for supporting Manta!

**Comment by Dengjianping** [comment]
Seems fixed
