### ISSUE TITLE
Not able to connect peers for manta testnet

### ISSUE THREAD

**Issue by abhiyana** [Manta-Network/Manta#1311]
I am trying to run node for manta-testnet using docker but the peers and best blocks are showing 0

## Steps to reproduce
Run below command 
```docker run --platform=linux/amd64 -it --entrypoint=/usr/local/bin/manta mantanetwork/manta:latest --chain=manta-testnet -- --chain=rococo```

### Expected Behaviour
Should able to connect to peers and best blocks should not be zero

### System
OS: Mac OS

**Comment by ferrell-code** [comment]
Yeah our docker image is not maintained right now and pretty old

For now use the raw binary built in the release (or compile from source).

We will start maintaining a docker image at some point in the near future

**Comment by Dengjianping** [comment]
Seems fixed
