### ISSUE TITLE
Manta token stuck during bridging from Pacific to Atlantic.  Could not find on Moonbeam network either.  Pls help

### ISSUE THREAD

**Issue by geomarlboro** [Manta-Network/Manta#1319]
Hi
I was trying to bridging Manta token from Pacific (metamask wallet) to Atlantic (Talisman wallet), and it seemed the token got stuck in the bridge.  After reading some of the posts here, I think it most likely is on the moonbeam network, but I was having trouble helping it.  Could you please help with this issue.  
https://pacific-explorer.manta.network/tx/0xfc8bfc812480a6e085c93939a476ac90481516d4bafbcf4a4443d771819c8a59

most appreciated.

Geo

**Comment by ferrell-code** [comment]
Your token is on moonbeam: https://moonscan.io/address/0x85C1821E1Df3d4d06Ad64a0F28DeA49c718a7D01

**Comment by geomarlboro** [comment]
Thanks.  So now I need to send Manta token from moonbeam network to Atlantic using the same UI on manta network, correct?  I also need to have some GLMR for gas.  This may seem like a dumb question, but how do I add GLMR to moonbeam network to pay for the gas fee?

**Comment by Dengjianping** [comment]
If it's not fixed, please go our community, https://discord.com/channels/795390654628102165/837322567127400478

**Comment by Truemann83** [comment]
> Hi I was trying to bridging Manta token from Pacific (metamask wallet) to Atlantic (Talisman wallet), and it seemed the token got stuck in the bridge. After reading some of the posts here, I think it most likely is on the moonbeam network, but I was having trouble helping it. Could you please help with this issue. https://pacific-explorer.manta.network/tx/0xfc8bfc812480a6e085c93939a476ac90481516d4bafbcf4a4443d771819c8a59
> 
> most appreciated.
> 
> Geo

Hi!
Please help!
How did you resolve your problem?
I still cant find my Manta tokens((
