### ISSUE TITLE
How to running manta pacific full node？

### ISSUE THREAD

**Issue by orange723** [Manta-Network/Manta#1324]
Url is “https://docs.manta.network/docs/manta-pacific/Replica%20Node”

Download [manta-replica-main.zip](https://docs.manta.network/assets/files/manta-replica-main-6df0cd69585a8d05e72240a8dfd0478a.zip)

set image to public.ecr.aws/i6b2w2n6/op-node:celestia-3.0.0 and L2 url is self running eth.
log output always 

"INFO [03-13|03:17:38.545] Starting work on payload                 id=0x681e7cce1f3a9731
INFO [03-13|03:17:38.550] Imported new potential chain segment     number=1,581,488 hash=2fb0c3..7b6f56 blocks=1 txs=1 mgas=0.051 elapsed=2.977ms     mgasps=16.965 age=3d30m19s snapdiffs=1.46MiB    triedirty=0.00B
INFO [03-13|03:17:38.553] Chain head was updated                   number=1,581,488 hash=2fb0c3..7b6f56 root=23e3ac..62ce66 elapsed=1.943941ms  age=3d30m19s"

blocknumber always not new

help me, how to fix this problem.

**Comment by Dengjianping** [comment]
Please go our community, there're pacific engineers who can help.
https://discord.com/channels/795390654628102165/837322567127400478
