### ISSUE TITLE
Manta<>Shawn

### ISSUE THREAD

**Issue by stechu** [Manta-Network/Manta#134]
1. setting constants:
a. AVERAGE_ON_INITIALIZE_RATIO

```rust
/// We assume that ~5% of the block weight is consumed by `on_initialize` handlers. This is
/// used to limit the maximal weight of a single extrinsic.
pub const AVERAGE_ON_INITIALIZE_RATIO: Perbill = Perbill::from_percent(5);
/// We allow `Normal` extrinsics to fill up the block up to 75%, the rest can be used by
/// Operational  extrinsics.
pub const NORMAL_DISPATCH_RATIO: Perbill = Perbill::from_percent(75);

/// We allow for 0.5 seconds of compute with a 6 second average block time.
pub const MAXIMUM_BLOCK_WEIGHT: Weight = WEIGHT_PER_SECOND / 2;

// 5MB
pub RuntimeBlockLength: BlockLength =
		BlockLength::max_with_normal_ratio(5 * 1024 * 1024, NORMAL_DISPATCH_RATIO);
```

for example, Acala use a different value:
```rust
// TODO: somehow estimate this value. Start from a conservative value.
pub const AVERAGE_ON_INITIALIZE_RATIO: Perbill = Perbill::from_percent(10);
/// The ratio that `Normal` extrinsics should occupy. Start from a conservative value.
const NORMAL_DISPATCH_RATIO: Perbill = Perbill::from_percent(70);
```

b.  `MaxInvulnerables` setting
```rust
parameter_types! {
	// Pallet account for record rewards and give rewards to collator.
	pub const PotId: PalletId = PalletId(*b"PotStake");
	// How many collator candidates is allowed.
	pub const MaxCandidates: u32 = 10;
	pub const MinCandidates: u32 = 3;
	// How many collators who cannot be slashed.
	pub const MaxInvulnerables: u32 = 10;
}
```

c. We make period shorter (from Acala's experience)
```rust
parameter_types! {
	pub const DisabledValidatorsThreshold: Perbill = Perbill::from_percent(33);
	// Rotate collator's spot each 3 hours.
	pub const Period: u32 = 3 * HOURS;
	pub const Offset: u32 = 0;
}
```

d. pallet_transaction_payment
```rust
parameter_types! {
	/// Relay Chain `TransactionByteFee` / 10
	pub const TransactionByteFee: Balance = mMA; // 10^12 / 1_000
}
```

**Comment by Dengjianping** [comment]
Questions about governance.

1. When should we allow democracy && When to remove sudo? How many members we should consider?
2. As a parachain, do we need technical committee?

**Comment by ghzlatarev** [comment]
I have a few questions about accessing pallets' storage externally.Here's a minimal example:

https://github.com/ghzlatarev/derive-pallet-assets-trait-error-2/blob/master/pallets/template/src/lib.rs#L82-L88

Most of the functions that modify storage seem to be ``pub(super)`` so if my understanding is correct they shouldn't be accessible outside the crate, right ? 
Then how should I go about modifying pallet-assets storage in the example ? Maybe it's not a good idea in principle ?
The extrinsics are ``pub fn`` but I don't think I can call them from the code, right ?

**Comment by ghzlatarev** [comment]
I've also got a few random questions about Polkadot, networks and consensus. I'm doing my own research but if you can point me to good resources or help me with some explanations on any one of these, that would be great.

- What can't be upgraded with runtime upgrade and needs to absolute be correct at genesis.

......................................................................................................................................................................................................

- What are examples of non-compliance in Polkadot ? Stuff that would trigger slashing ?
- What are other examples of punishment and how are they triggered ?
- What are cartels in a Consensus mechanism and what are strategies to resist them ?

......................................................................................................................................................................................................

- How can it be attempted to DDoS a network. Any "dangerous" extrinsics ?
- What is a Sybil attack and defense mechanisms ?

......................................................................................................................................................................................................

- Why do forks happen in BABE ?
- How can someone try to subvert the NPoS election process ? What are protections for that ?

......................................................................................................................................................................................................

- What is the Parity process bot exactly and what do you guys use it for ? Can it be used by anyone?
