### ISSUE TITLE
Multisig SUDO account

### ISSUE THREAD

**Issue by stechu** [Manta-Network/Manta#139]
Before we move to decentralized governance, we would like to have a sudo account which is a multisig account. 
We need to generate the multisig account and then test it.

**Comment by Dengjianping** [comment]
I tested it in substrate, it worked. And related doc: https://github.com/Manta-Network/Manta/wiki/How-to-use-a-mulsig-sudo-account
But while I tried it in calamari, the error happened to me like we did it last time:
`Uncaught error. Something went wrong with the query and rendering of this component. api.rpc.payment.queryInfo is not a function`.

It's pretty obvious, our calamari node is missing payment rpc service, so we have to add this rpc back.
I tried to add this rpc to our node, and worked with mulsignature.
I'll submit a pr to fix it.
