### ISSUE TITLE
Cargo check and Cargo Test panicked during incremental compilation

### ISSUE THREAD

**Issue by stechu** [Manta-Network/Manta#22]
Currently, `cargo check` and `cargo test` will panic, `cargo build --release` is fine. I believe this is a rust bug rather a manta bug, submitted an issue to Rust:

https://github.com/rust-lang/rust/issues/84885

**Comment by stechu** [comment]
Can get a workaround by running:
```
cargo clean
```
as suggested https://github.com/rust-lang/rust/issues/84341
In a nutshell, this bug only happens when doing incremental compilation 
Will keep this issue open until rust team fix this bug

**Comment by Dengjianping** [comment]
Fixed by latest rust.
