### ISSUE TITLE
Add test cases for checking important chain states after runtime upgrade

### ISSUE THREAD

**Issue by Dengjianping** [Manta-Network/Manta#236]
In case we don't lose data after runtime upgrade, we need add test cases to check important chain states, like
`pallet-balances`, `democracy ` related pallets.

`polkadot-js` is convenient tool for write these test cases. 

`try-runtime` is another way to go. Continue https://github.com/Manta-Network/Manta/issues/122

**Comment by Garandor** [comment]
closing as not done since this is a duplicate
