### ISSUE TITLE
A new pallet for banning/allowing specific modules or extrinsics.

### ISSUE THREAD

**Issue by Dengjianping** [Manta-Network/Manta#248]
white list pallet.

Perhaps this new pallet can fix our problem.
https://github.com/paritytech/substrate/pull/10159

**Comment by stechu** [comment]
> white list pallet.
> 
> Perhaps this new pallet can fix our problem. [paritytech/substrate#10159](https://github.com/paritytech/substrate/pull/10159)

I think this whitelist pallet is doing something different.

I think we want something like https://github.com/AcalaNetwork/Acala/tree/master/modules/transaction-pause

**Comment by Dengjianping** [comment]
Yeah, this implementation looks straightforward and not that hard.

What about this pallet: https://github.com/paritytech/substrate/pull/10197
