### ISSUE TITLE
Error when running a validator node 

### ISSUE THREAD

**Issue by King-Charming** [Manta-Network/Manta#249]
After building the node with cargo I downloaded calamari-pc from the latest release and put it in ./target/release 

When I turned on the node I got a few errors and from the telemetry, it seems to not be connecting correctly. The errors I got was: 
1. error=Runtime(RuntimeRequest(RuntimeApiError("Application(Execution(Other(\"Exported method ParachainHost_availability_cores is not found\")))"))) ctx="Error in Requester::update_fetching_heads"
2. Failed to fetch runtime API data for job err=RuntimeApiError("Application(Execution(Other(\"Exported method ParachainHost_validator_groups is not found\")))")
3. error=Sender(Runtime(RuntimeRequest(RuntimeApiError("Application(Execution(Other(\"Exported method ParachainHost_session_index_for_child is not found\")))")))) ctx="on FromOverseer"
4. job finished with an error job="BitfieldSigningJob" parent_hash=0xb0a8…dafe err=Util(RuntimeApi(RuntimeApiError("Application(Execution(Other(\"Exported method ParachainHost_session_index_for_child is not found\")))")))
5. Failed to fetch basics from runtime API err=RuntimeApiError("Application(Execution(Other(\"Exported method ParachainHost_session_index_for_child is not found\")))")
6. Our view contains 0xb0a8…dafe but the overseer never told use we should work on this added=0xb0a8…dafe

**Comment by Dengjianping** [comment]
Actually, it's fine. It causes by relaychain, because relaychain didn't support parachain at the beginning. These errors only shows while starting calamari node.

We don't send data to polkadot telemetry. We have our own telemetry server.

**Comment by King-Charming** [comment]
Okay, thank you. Is the telemetry on your own server public so I can check the node there?

**Comment by Dengjianping** [comment]
Sure, just check it here: https://telemetry.manta.systems/#/Calamari%20Parachain
