### ISSUE TITLE
After a node starts synchronizing to the latest block, it will stop in a block for a long time, even if it is restarted. The current node version is the latest version

### ISSUE THREAD

**Issue by COLUD4** [Manta-Network/Manta#286]
![截屏2021-11-26 下午7 48 21](https://user-images.githubusercontent.com/21240219/143576626-aedecde3-0e4d-4800-ba55-6a673d091db9.png)

**Comment by Dengjianping** [comment]
Thanks for reporting this problem.
Perhaps you have to wait your node to catch up relaychain's blocks. Your node is still lagging behind relaychain(`target=1246233`), but currently, the latest block number in kusama is bigger than `10264615`.
