### ISSUE TITLE
 LTO optimization for binary generation

### ISSUE THREAD

**Issue by Dengjianping** [Manta-Network/Manta#289]
Related issue: https://github.com/paritytech/polkadot/issues/4311

Not sure whether it will occur in `polkadot-v0.9.13`.

**Comment by stechu** [comment]
Indeed, maybe we can experiment that for the next release? cc @ghzlatarev

**Comment by ghzlatarev** [comment]
# Benchmarking

Without LTO - https://github.com/Manta-Network/Manta/actions/runs/1627848446
With LTO - https://github.com/Manta-Network/Manta/actions/runs/1627848281

Compilation time was increased by 30 minutes from half hour to an hour.

## Samples:
### pallet-balances (before vs after):
* transfer() - 136_309_000 vs 87_921_000
* transfer_keep_alive() - 99_370_000 vs 64_661_000
* set_balance_creating() 52_630_000 vs 35_050_000

### pallet-collective (before vs after):
* execute() - 39_571_000 vs 26_335_000
* propose_proposed() - 71_509_000 vs 44_163_000
* vote() 64_624_000 vs 48_205_000

### pallet-democracy (before vs after):
* propose() - 118_151_000 vs 86_491_000
* second() - 70_268_000 vs 48_933_000
* vote_new() 78_750_000 vs 56_050_000
