### ISSUE TITLE
Calamari/Manta Performance Test Tracking Issue

### ISSUE THREAD

**Issue by Dengjianping** [Manta-Network/Manta#290]
What factors we should consider while test TPS for calamari/manta.
- Extrinsic size
- Block size
- Transactions count
- When to reach peak
- When to decline
- Collator count
- How Fee change while more transactions get into one block
- The size of Transaction queue
- Computer configuration
- Network condition

**Comment by Dengjianping** [comment]
![image](https://user-images.githubusercontent.com/1914204/144240214-e58682fe-6ea1-4d61-b69c-e2a57bc30a3a.png)

I started test TPS on M1, got this result. So the TPS on calamari runtime is 
```
block-time = 12s;
transaction-count = 860;
TPS = transaction-count / block-time = 71.66;
```

**Comment by Dengjianping** [comment]
Did some optimizations on [wasm build](https://github.com/Manta-Network/Manta/blob/manta/runtime/calamari/build.rs):
- `opt-level=3`
- `link-time-optimizations`(lto)
=> 
```rust
fn main() {
    WasmBuilder::new()
        .with_current_project()
        .export_heap_base()
        .import_memory()
        .append_to_rust_flags("-C opt-level=z")
        .append_to_rust_flags("-C linker-plugin-lto")
        .build()
}
```
Reference: https://rustwasm.github.io/book/reference/code-size.html#compiling-with-link-time-optimizations-lto

But it seems it would not help, got the same result.

**Comment by Dengjianping** [comment]
There're two params related to transactions.
```
--pool-kbytes <COUNT>
        Maximum number of kilobytes of all transactions stored in the pool [default: 20480]
--pool-limit <COUNT>
        Maximum number of transactions in the transaction pool [default: 8192]
```
I doubled both the value of params, didn't help.

**Comment by stechu** [comment]
I suggest to add a firerate control mechanism, a reference implementation can be found here:

https://github.com/algorand/go-algorand/pull/402

Additionally, measure the following metrics:

- avg. number of extrinsics in a single block
- avg. block time

TPS could be calculated from the above two metrics.

**Comment by Dengjianping** [comment]
Latest tps on M1.
```
block-time = 12s;
transaction-count = 1140;
TPS = transaction-count / block-time = 95;
```
