### ISSUE TITLE
Reduce Minimal Validator Count 

### ISSUE THREAD

**Issue by stechu** [Manta-Network/Manta#292]
Change minimal validator count for Dolphin to 3 (The current number of validators is 5, and the actual deployed validator is also 5, which leaves zero margin).

- [ ] change the minimal validator count for Dolphin to 3
- [ ] update the `dolphin-testnet` json chain spec

**Comment by Garandor** [comment]
Minimum candidate count was removed from manta-collator-selection. Closing.
