### ISSUE TITLE
Remove clippy warnings

### ISSUE THREAD

**Issue by Dengjianping** [Manta-Network/Manta#30]
When I tried clippy check, there're some clippy warnings, we need to make clippy happy.
```
cargo +nightly clippy
```
And we might have a new convention that developers need do clippy check before push code.
And clippy can teach us how to write elegant code.

**Comment by zhenfeizhang** [comment]
I second this.

**Comment by zhenfeizhang** [comment]
Current issue with Clippy is caused by `pallet-manta-pay`.
This issue https://github.com/Manta-Network/pallet-manta-pay/issues/19 tracks the problem

**Comment by zhenfeizhang** [comment]
Problem solved with #31
