### ISSUE TITLE
Clean up clippy warnings

### ISSUE THREAD

**Issue by ghzlatarev** [Manta-Network/Manta#307]
For example in https://github.com/Manta-Network/Manta/runs/4608072266?check_suite_focus=true
There are warnings like:
`warning: casting integer literal to u64 is unnecessary`

Can use `#![allow(clippy::unnecessary_cast)]` for the custom weight files warnings.

**Comment by binsta** [comment]
Can I take this one?

**Comment by Dengjianping** [comment]
> Can I take this one?

Sure! We welcome any contribution from community!
