### ISSUE TITLE
Pin a nightly rust for our CI/CD 

### ISSUE THREAD

**Issue by ghzlatarev** [Manta-Network/Manta#322]
For reference - https://github.com/AcalaNetwork/Acala/blob/master/.github/workflows/test.yml#L39

**Comment by ghzlatarev** [comment]
Revert the CI workaround https://github.com/Manta-Network/Manta/pull/571 which pins the tests and publish-draft-release workflows to: 
```
rustup toolchain install nightly-2022-07-10-x86_64-unknown-linux-gnu
rustup target add wasm32-unknown-unknown --toolchain nightly-2022-07-10-x86_64-unknown-linux-gnu
```

**Comment by Dengjianping** [comment]
Cargo supports `[toolchain]` section.
```
[toolchain]
channel = "nightly-2022-07-10"
components = [ "rustfmt", "clippy" ]
targets = [ "wasm32-unknown-unknown" ]
```

**Comment by Garandor** [comment]
resolved by https://github.com/Manta-Network/Manta/commit/eb05731bb7074ab1dcd5b874805c32ff7b2fa239
