### ISSUE TITLE
Github integration into Notion

### ISSUE THREAD

**Issue by ghzlatarev** [Manta-Network/Manta#333]
https://github.com/makenotion/notion-sdk-js/tree/main/examples/notion-github-sync

**Comment by ghzlatarev** [comment]
The issues have been imported `Github Issues` in Notion using the `notion-github-sync` example https://github.com/makenotion/notion-sdk-js/tree/main/examples/notion-github-sync
However this includes limited information, like name, number of comments. We need at least the linked PRs as well to make this more useful.

**Comment by Garandor** [comment]
closing for now, no work planned
