### ISSUE TITLE
QA Template

### ISSUE THREAD

**Issue by Dengjianping** [Manta-Network/Manta#345]
1. What're kind of tests we must cover before publish a release.
   a. runtime upgrade.
   b. block production.
   c. front-end.
   d. bugs fix, new features and improvements,
   e. ...
2. Who is going to be responsible for the QA.
3. How long the QA will take.

**Comment by ghzlatarev** [comment]
@Dengjianping use this as well https://hackmd.io/TbFmorG2RnOPmLuFcg9JOQ?view

**Comment by Garandor** [comment]
resolved and tracked in notion
