### ISSUE TITLE
[Trial]Enable LTO for wasm build

### ISSUE THREAD

**Issue by Dengjianping** [Manta-Network/Manta#346]
Now we only enabled LTO for native build. If someone is interested in this issue, just check this build.rs:
https://github.com/Manta-Network/Manta/blob/manta/runtime/calamari/build.rs
```rust
fn main() {
    WasmBuilder::new()
        .with_current_project()
        .export_heap_base()
        .import_memory()
        .append_to_rust_flags("-C opt-level=z")
        .append_to_rust_flags("-C linker-plugin-lto")
        .build()
}
```

Re-benchmark pallets to see whether the performance is improved.

**Comment by ghzlatarev** [comment]
@Dengjianping also when building with SRTool ?

**Comment by ghzlatarev** [comment]
https://github.com/paritytech/substrate/pull/10747/files

https://github.com/paritytech/substrate/issues/10608

**Comment by Dengjianping** [comment]
> https://github.com/paritytech/substrate/pull/10747/files

I feel confused about this pr, why some benchmark go down a little bit.

**Comment by Dengjianping** [comment]
I tried to enable LTO for wasm build, seems almost identical, some result are even worse.
And you can look at the result in substrate, the same to us.

For now, I don't think it will improve the performance a lot.
