### ISSUE TITLE
Dolphin V2 Runtime

### ISSUE THREAD

**Issue by stechu** [Manta-Network/Manta#349]
We should have a new parachain runtime that serves:
1. Test New Features
2. Work as bases for Dolphin Testnet V2 
3. This new runtime should be part of the unified binary of `Calamari/Manta`

# Configuration

For now, the configuration should be identical to `calamari` with the following differences:
1. The token symbol is `DOL`, with decimal 18 (ERC-20 compatible)
2. The SUDO keys are different, however, it should be identical to the old `dolphin`'s SUDO keys (there might be some necessary difference need to be made in the chain-spec accordingly)
3. Dolphin V2 doesn't need `CalamariVesting` pallet

# Things to figure out

1. how should we build CI/CD for Dolphin runtime?

**Comment by Dengjianping** [comment]
What's the name of new runtime?

**Comment by stechu** [comment]
Should be just dolphin (this time dolphin is a parachain runtime)
