### ISSUE TITLE
Equivocation Error

### ISSUE THREAD

**Issue by stechu** [Manta-Network/Manta#35]
Error from testnet running log:

```
2021-05-10 05:36:18 Error reporting prevote equivocation: Safety("Refraining from sending equivocation report for our own equivocation.")
```

**Comment by Dengjianping** [comment]
I found a post from parity, talking about consensus security problem. I quote a related part here:
> A more serious transgression is equivocation. Equivocation can occur in both BABE and GRANDPA. In BABE, equivocation is producing two blocks in the same slot. In GRANDPA, it is sending pre-vote or pre-commit messages for two chains that conflict with each other in the same round. Equivocation comes with a severe slash. If too many validators equivocate, it would be impossible to select a single, canonical chain.

More details, go to this link: https://polkadot.network/polkadot-consensus-part-4-security/

**Comment by stechu** [comment]
It appears that the error is caused by mis-configuration of session keys. Close it for now.
