### ISSUE TITLE
Implement a feature like fast-runtime

### ISSUE THREAD

**Issue by Dengjianping** [Manta-Network/Manta#357]
A feature `fast-runtime` from https://github.com/paritytech/polkadot/pull/4332.

This feature can help us shorten epoch/session time, very convenient for test.
Implementation: https://github.com/paritytech/polkadot/blob/master/runtime/common/src/lib.rs#L215

**Comment by Garandor** [comment]
I'll give implementing it a try, it would come in handy with testing of #358
