### ISSUE TITLE
Fee related unit tests

### ISSUE THREAD

**Issue by stechu** [Manta-Network/Manta#36]
Fee related unit tests, could be similar to:
https://github.com/paritytech/substrate/blob/master/bin/node/runtime/src/impls.rs

**Comment by ghzlatarev** [comment]
A few thoughts on the issue: ​
* If we can acquire the numeric value of the worst case scenario, the automatic benchmarking system generates, we can then compare it to the actual weight value during runtime/test (if that can be queried as well)
* We can also check that the actual weight is non-zero, if it is supposed to be, or vice versa.
* We can make QA tests that would run a couple of nodes, run the front end polkadot js app, and fire a few extrinsics. There is software like Sikuli for such purposes, but I'd say this is low priority for now.
