### ISSUE TITLE
Community collators health checks

### ISSUE THREAD

**Issue by ghzlatarev** [Manta-Network/Manta#363]
We need a basic mechanism to get alerts from the community collators. If they are skipping blocks or stop production altogether.

**Comment by rishabhfsd** [comment]
@ghzlatarev 
Shall we try to implement monitoring stack in collator's dockerfile ?
- Prometheus
- Alertmanager
These two are enough to get done our basic purpose.

**Comment by Garandor** [comment]
=> https://sparta.calamari.systems/
