### ISSUE TITLE
Add Pallet Weight Benchmarking Documentation

### ISSUE THREAD

**Issue by bhgomes** [Manta-Network/Manta#366]
When trying to benchmark a pallet to compute extrinsic weights we need to do something like the following:

1. Include the pallet we want to benchmark in the node (can we just add it as a dependency or do we need to also integrate it into `runtimes/manta/runtime/src/lib.rs`?)
2. Build the node as `cargo build --release --features="runtime-benchmarks"`
3. Run the benchmark:
    ```rust
    ./target/release/manta benchmark \
        --chain=calamari-local \
        --pallet={PALLET_NAME} \
        --extrinsic="*" \
        --execution=Wasm \
        --wasm-execution=Compiled \
        --heap-pages=4096 \
        --repeat=20 \
        --steps=50 \
        --output={OUTPUT_WEIGHT_FILE}
    ```

Is this true for general pallets? Is there a more streamlined way to do this kind of measurement? It would be nice to have some documentation on the strategy for benchmarking here.

**Comment by ghzlatarev** [comment]
1. You need to integrate it into the runtime as well. And you need to modify these two: 
    https://github.com/Manta-Network/Manta/blob/manta/runtime/calamari/src/lib.rs#L1053-L1066
    https://github.com/Manta-Network/Manta/blob/manta/runtime/calamari/src/lib.rs#L1100-L1114
2. Yes
3. Yes, this is pretty general. You can make the `--chain` argument configurable as well.
4. In general the strategy is to re-benchmark any time something in the runtime changes. We have a couple of automated jobs where we've listed the pallets we want to benchmark for Calamari and Manta:
    https://github.com/Manta-Network/Manta/actions/workflows/generate_calamari_weights_files.yml
    https://github.com/Manta-Network/Manta/actions/workflows/generate_manta_weights_files.yml
    You can trigger these manually and choose a branch on which to run them. These CI jobs are always going to use the same bare-metal AWS instances to do the benchmarks. They also use optimized binaries like our releases.


Anyway I'll document this in Notion.

**Comment by ghzlatarev** [comment]
https://www.notion.so/2d9269c2bb794ee0a1d05ab3ee3935ee?v=1932353a72ee44b586caaee9e28e00c5
