### ISSUE TITLE
Better Integration Test

### ISSUE THREAD

**Issue by stechu** [Manta-Network/Manta#370]
Many things currently we do in QA test can be performed in an automated fashion, for example:

https://github.com/PureStake/moonbeam/blob/master/runtime/moonbeam/tests/integration_test.rs

Related to #347

**Comment by ghzlatarev** [comment]
Duplicate of https://github.com/Manta-Network/Manta/issues/347

**Comment by ghzlatarev** [comment]
Not a duplicate. my bad.
