### ISSUE TITLE
Provide easy mechanism for collator runners to benchmark their machines

### ISSUE THREAD

**Issue by ghzlatarev** [Manta-Network/Manta#390]
The easy solution is https://dev.kilt.io/docs/chain/collator/#benchmarking We can outline how a collator runner can benchmark their machine. Basically let them build a binary with the runtime-benchmarks flag and optimizations, run the benchmark and compare to our official weights. If their weights are lower or insignificantly higher, then the machine should be fine 
or we can provide a benchmarking binary as one of the release artifacts

The other solution is to implement a subcommand similar to polkadot's https://github.com/paritytech/polkadot/blob/master/cli/src/command.rs#L442
This checks pvf generation time, which is not exactly the what we want for collators. but we could implement something similar. The baseline benchmark looks okay.

**Comment by Garandor** [comment]
This should be addressed by upstream https://github.com/paritytech/substrate/pull/11198

We just need to create docs for it
