### ISSUE TITLE
Free storage of now-unused pallet_collator_selection on Calamari 

### ISSUE THREAD

**Issue by Garandor** [Manta-Network/Manta#412]
Forking the pallet created new StorageItems with different keys, leaving the old ones left over as dead memory on the live calamari chain as we did not execute a migration from old to new. 

To fix this, either 
`remove_storage_prefix("OldPalletNameInYourRuntime", "LastAuthoredBlock", &[]);` must be used in a runtime migration 

> Or you could also send a transaction to your chain [kill_storage](https://docs.rs/frame-system/latest/frame_system/pallet/enum.Call.html#variant.kill_storage). Be aware that this call requires root. As argument you pass a vector with the only element being the raw key of the old storage item (hash(pallet_collator_selection)hash(LastAuthoredBlock)).

See the original question: https://substrate.stackexchange.com/questions/506/forked-parity-pallet-didnt-migrate-storage-deployed-to-chain-how-to-clear-or

Items of `pallet_collator_selection` that need killing:
- Invulnerables
- Candidates
- LastAuthoredBlock
- DesiredCandidates
- CandidacyBond

This would require 5 governance'd TXs, so the fix through a RT upgrade is likely the better option

**Comment by ghzlatarev** [comment]
The module name did not change when we forked so this is not required.
Only the `MinCandidates` storage item which was actually removed needs to be drained https://github.com/Manta-Network/Manta/issues/413
