### ISSUE TITLE
Drain `CollatorSelection`'s `MinCandidates` storage item

### ISSUE THREAD

**Issue by ghzlatarev** [Manta-Network/Manta#413]
Before forking `pallet_collator_selection` it had a `MInCandidates` storage item which wasn't drained when we migrated. This is only a `u32` but it it's bad practice to leave the memory unclaimed. https://substrate.stackexchange.com/questions/504/reclaim-used-space-of-a-removed-storageitem-on-a-live-chain

Two ways to do this:

1. use [remove_storage_prefix](https://docs.rs/frame-support/latest/frame_support/storage/migration/fn.remove_storage_prefix.html). This needs to be placed into a runtime migration. 

2. send a `kill_storage` transaction on-chain, which requires root. As argument you pass a vector with the only element being the raw key of the old storage item (hash(pallet_collator_selection)hash(MinCandidates)).

**Comment by Garandor** [comment]
```
use hex::encode;
use sp_core::twox_128;
let h1 = twox_128(b"CollatorSelection");
let h2 = twox_128(b"MinCandidates");
println!("0x{}", encode(&h1));
println!("0x{}", encode(&h2));
println!("0x{}{}", encode(&h1), encode(&h2));
```
produces
```
0x15464cac3378d46f113cd5b7a4d71c84
0x5d6b1b74f42c7633615f9ce7932f357c
0x15464cac3378d46f113cd5b7a4d71c845d6b1b74f42c7633615f9ce7932f357c
```
but when i plug it into state_getStorage, i get back none:
 
![image](https://user-images.githubusercontent.com/4237655/156106823-8fed9481-2dac-4583-a6ce-9ebc35115556.png)

@ghzlatarev any idea if my input into the twox_hash is wrong passing the ascii string? 
~Or could it be that you guys actually already killed that storage item?~ CollatorSelection and MaxCandidates also returns none...
I'll keep looking tmrw

**Comment by Garandor** [comment]
I think i'm missing the scale encoding step of the string, frame_support instead of sp_core runs 

> /home/manta/.cargo/git/checkouts/substrate-7e08433d4c370a21/19162e4/frame/support/src/hash.rs

```
	fn twox_128(&self) -> [u8; 16] {
		self.using_encoded(twox_128)
```

**Comment by ghzlatarev** [comment]
@Garandor not quite sure myself about your question. Tried a few things but getting `none` results always so gotta look into it a bit more.
I'd suggest to check out some of the storage tests in Substrate maybe

**Comment by ghzlatarev** [comment]
@Garandor you can do the following:
```
	let prefix = |pallet_name, storage_name| {
		let mut res = [0u8; 32];
		res[0..16].copy_from_slice(&Twox128::hash(pallet_name));
		res[16..32].copy_from_slice(&Twox128::hash(storage_name));
		res.to_vec()
	};

	println!(
		"0x{:?}",
		hex::encode(prefix(b"CollatorSelection", b"MinCandidates"))
	);
	println!(
		"0x{:?}",
		hex::encode(prefix(b"CollatorSelection", b"DesiredCandidates"))
	);
```

The `Desired Candidates` prefix - `0x15464cac3378d46f113cd5b7a4d71c84476f594316a7dfe49c1f352d95abdaf1` will return a value when you query it on Calamari.
However the `MinCandidates` prefix - `0x15464cac3378d46f113cd5b7a4d71c845d6b1b74f42c7633615f9ce7932f357c` returns `none`. Probably because it was never actually set in the first place.
