### ISSUE TITLE
Adapt Dolphin RT to use fast_or_prod macro

### ISSUE THREAD

**Issue by Garandor** [Manta-Network/Manta#415]
Dolphin V2 RT was built before #383 was merged, so it has hardcoded short timers.

After merging #383 we should 
- adapt the Dolphin Runtime to use `fast_or_prod` with the current timers in the `fast` case, and calamari productive timings in the `prod` case.
- tell everyone to build the RT with `--features=fast-runtime` for testing

Child of #357

**Comment by ghzlatarev** [comment]
Closed with https://github.com/Manta-Network/Manta/pull/493
