### ISSUE TITLE
Metamask support

### ISSUE THREAD

**Issue by dziabko** [Manta-Network/Manta#417]
Need to support H160 addresses on Metamask to be able to sign and send transactions using Metamask.

Substrate based chains use SS58 address format which uses H256. In order to send transactions from Metamask, we need to be able to support H160 addresses either through Unified accounts, or by mapping H160 addresses to H256 addresses.
Either scenario, we would have to implement an H256 to H160 address converter.

We also might need to update our Polkadot.js interface to allow users to add/support H160 accounts. https://docs.moonbeam.network/learn/features/unified-accounts/
Moonbeam's updated Polkadot.js interface (https://github.com/PureStake/apps)

**Comment by Garandor** [comment]
@BoyuanFeng can this have a prototype by Aug 12 or is that too early?

**Comment by BoyuanFeng** [comment]
> @BoyuanFeng can this have a prototype by Aug 12 or is that too early?

I am still working on manta-rs such as circuits and trusted setup migration. I need to find a time later for Metamask support.

**Comment by Garandor** [comment]
closing for now, no work planned
