### ISSUE TITLE
Collator Application <> Sik | crifferent.de

### ISSUE THREAD

**Issue by SimonKraus** [Manta-Network/Manta#428]
@grenade allow me to introduce myself: 
 - I am Simon Kraus (nickname Sik is just a abbrev of SImonKraus)
 - 10+ years of Dev and DevOps experience
 - running crifferent.de since 2014
 - also web3 dApps dev for Staking Facilities
 - strong community focus (Admin/Moderator/Ambassador/Councillor/Registrar for many DotSama projects)
 - operating nodes for Polkadot/Kusama/Moonbeam/Moonriver/Astar/Shiden/Kilt/Centrifuge and others

I had one of the first running Calamari nodes even before the instructions were released and I helped others in the collator channels and through DMs.
Also directly provided the needed KMA balance on the account dmyyAnvDKvWePe7d6yWzVnqVhJp9HbNMs5RDoKjUSABNQcVf5 and connected account and node.

I am happy to help testing and debugging on a professional level whenever you need assistance from outside of the team.

Feel free to schedule a call anytime to touch base.

**Comment by grenade** [comment]
closing as we have a dialogue elsewhere
