### ISSUE TITLE
Calamari: Migrate all pallets from PalletVersion to StorageVersion 

### ISSUE THREAD

**Issue by Garandor** [Manta-Network/Manta#460]
Parity introduced a new versioning mechanism for its pallets, whereas it now has a (purely numeric) StorageVersion.
https://github.com/paritytech/substrate/pull/9165/

The pallets must be migrated to use the new mechanism and parity has created a helper function to do so:
https://paritytech.github.io/substrate/master/frame_support/migrations/fn.migrate_from_pallet_version_to_storage_version.html

**ATTN:** Instead of migrating the old PalletVersion number, parity's migration helper hard sets the storage version to whatever is set to be the StorageVersion in current code ( instead of what is on the chain )
-> `let version = <T as GetStorageVersion>::current_storage_version();`
**Care must be taken to ensure that all migrations were applied to the pallets before this migration is executed**

This must be applied during one of the next runtime upgrades and we should adapt our own pallets to use the same mechansim as well

**Comment by flame4** [comment]
Here append a official storage migration tracking doc by alex:  https://github.com/apopiak/substrate-migrations
