### ISSUE TITLE
Remove native runtime?

### ISSUE THREAD

**Issue by Dengjianping** [Manta-Network/Manta#469]
Currently, statemint has been switched to wasm runtime only.

https://github.com/paritytech/cumulus/pull/1054

**Comment by flame4** [comment]
some relative issue and discussions:  
https://github.com/paritytech/substrate/issues/7288
https://github.com/paritytech/substrate/pull/8893

**Comment by ghzlatarev** [comment]
@flame4 don't forget to move issues in progress when you are working on them
