### ISSUE TITLE
Using precomputed coin to speed up unittest

### ISSUE THREAD

**Issue by stechu** [Manta-Network/Manta#489]
Currently, the unit test of `manta-pay` requires computing private coin on the fly. We can improve the CI time by using pre-computed coins. 
This will weaken the `fuzzer` perspective of the test though.

**Comment by Garandor** [comment]
I think this is integrated already, right @ghzlatarev

**Comment by ghzlatarev** [comment]
No. This relates to the unit tests, but as Shumo has noted, it would weaken the randomization element of the tests, which I'm against.
So I'd also just close it.
