### ISSUE TITLE
Investigate sccache usage in the `check-tests.yml` workflow

### ISSUE THREAD

**Issue by ghzlatarev** [Manta-Network/Manta#503]
Currently the running time of this workflow doesn't seem to change between the first and successive runs.
Perhaps sccache is not working properly for some reason.
Needs to be investigated.

**Comment by ghzlatarev** [comment]
Could be related to the special features we're building with - https://github.com/Manta-Network/Manta/blob/manta/.github/workflows/check_tests.yml#L100

**Comment by Garandor** [comment]
Is this still an issue @ghzlatarev ?
