### ISSUE TITLE
Integrate audit tool into our CI

### ISSUE THREAD

**Issue by Dengjianping** [Manta-Network/Manta#508]
Currently, we're depending on so many crates, so I think we should have an audit tool for our project.
Before every time we publish a release, we should run this tool in CI.

https://crates.io/crates/cargo-audit

**Comment by Garandor** [comment]
As we keep building automation around releasing, I'm thinking it could be useful to reopen the discussion of having a `dev` branch and dedicated `release-xy` branches from there.

That way we could do things that need to be done on release (i.e. before merge to master or on commit to a `release-` branch)
- weight comparison with last release
- artifact deployment
- cargo audit

As part of a workflow that gets triggered to pushes on `release-` branches and separate it from stuff that gets executed on every PR commit like the normal test automation. See https://github.community/t/trigger-workflow-only-on-pull-request-merge/17359/14

e.g. 
- while a PR on a a release- branch is in `Draft` state, only normal testing is run on commit
- when it changes to `ready-for-review`, benchmarks, audit and metadata comparison are triggered
- after merge, i.e. on push to manta the release is automatically tagged and made public on social channels (forum discord etc)

We're doing tons of this stuff manually atm and it's not automatable with the current branch structure

**Comment by ghzlatarev** [comment]
> As we keep building automation around releasing, I'm thinking it could be useful to reopen the discussion of having a `dev` branch and dedicated `release-xy` branches from there.
> 
> That way we could do things that need to be done on release (i.e. before merge to master or on commit to a `release-` branch)
> 
> * weight comparison with last release
> * artifact deployment
> * cargo audit
> 
> As part of a workflow that gets triggered to pushes on `release-` branches and separate it from stuff that gets executed on every PR commit like the normal test automation. See https://github.community/t/trigger-workflow-only-on-pull-request-merge/17359/14
> 
> e.g.
> 
> * while a PR on a a release- branch is in `Draft` state, only normal testing is run on commit
> * when it changes to `ready-for-review`, benchmarks, audit and metadata comparison are triggered
> * after merge, i.e. on push to manta the release is automatically tagged and made public on social channels (forum discord etc)
> 
> We're doing tons of this stuff manually atm and it's not automatable with the current branch structure

Yes I agree, I've been meaning to do explore this for a while. Let's just make it a separate issue and make it medium priority

**Comment by Dengjianping** [comment]
cargo audit has been integrated into CI.
See the report: https://github.com/Manta-Network/Manta/runs/6416518299

**Comment by ghzlatarev** [comment]
So just upstream crates it seems.
