### ISSUE TITLE
`UntrustedTeleportLocation` while teleporting assets from Rococo

### ISSUE THREAD

**Issue by EclesioMeloJunior** [Manta-Network/Manta#521]
## Description

I am trying to transfer some assets from the Rococo relay chain to Dolphin parachain, just for testing. I submit the XCM limited teleport asset from the relay chain, the message arrives on the parachain but I got the following error:

```
{
  Incomplete: [
    1,000,000,000
    UntrustedTeleportLocation
  ]
}
```

So I was looking at the dolphin runtime at `manta/runtime/dolphin/src/lib.rs` and I notice on line [635](https://github.com/Manta-Network/Manta/blob/41fc16ed6d2b08170e522a724bb453645572e049/runtime/dolphin/src/lib.rs#L635) the following code:

```rs
parameter_types! {
...
>>      pub const RelayNetwork: NetworkId = NetworkId::Kusama;
...
}
```

Then I was wondering if the Dolphin runtime should have another RelayNetwork, for example, `NetworkId::Any`?

### Other informations

Here is the full payload of the XCM `xcmPallet.limitedTeleportAssets(dest, beneficiary, assets, feeAssetItem, weightLimit)`

```
dest: XcmVersionedMultiLocation
{
  V0: {
    X1: {
      Parachain: 2,084
    }
  }
}
```

```
beneficiary: XcmVersionedMultiLocation
{
  V0: {
    X1: {
      AccountId32: {
        network: Any
        id: 0x0ebc06ca0b2b4cabbf20f236db738d88939bcb550ebe75987b5dcc323f13ae28
      }
    }
  }
}
```

```
assets: XcmVersionedMultiAssets
{
  V0: [
    {
      ConcreteFungible: {
        id: Null
        amount: 3,000,000,000
      }
    }
  ]
}
```

```
feeAssetItem: u32
0
```

```
weightLimit: XcmV2WeightLimit
Unlimited
```

**Comment by ghzlatarev** [comment]
Hey thanks for reporting. The teleports from any chain, including the relay, are currently disabled with another configuration.
But let me take a look at the other part.

**Comment by Garandor** [comment]
To expand on that a bit: XCM transfers *are* possible, but only via the reserve-based transfer mechanism

**Comment by ghzlatarev** [comment]
`NetworkId::Any` variant is implicitly allowed. The point of the `RelayNetwork` configuration is to explictly allow another variant, so it is fine as it is.
