### ISSUE TITLE
A trait for method to do sanity check on all multilocations we support.

### ISSUE THREAD

**Issue by Dengjianping** [Manta-Network/Manta#564]
https://github.com/Manta-Network/Manta/pull/481#discussion_r879516428

**Comment by Garandor** [comment]
https://github.com/Manta-Network/Manta/pull/481/files/bbe49e526d1e2fedbb671a8c7fcdc06422252cf9#diff-0da041c944b5a8ca26aaae94530c2697f5cabe129ca90cb76b79c4f823d5c5beR476
