### ISSUE TITLE
Investigate splitting up the publish_draft_releases workflow

### ISSUE THREAD

**Issue by Garandor** [Manta-Network/Manta#608]
[publish_draft_releases.yml](https://github.com/Manta-Network/Manta/blob/manta/.github/workflows/publish_draft_releases.yml) currently contains

- integration tests
- docker test
on normal PRs

and the draft release generation on release candidates.

I open the file, see 1152 lines and immediately feel regret for doing so.

To reduce complexity and in the spirit of single-responsibility we should refactor this into multiple files, so that `publish_draft_releases` does exactly what the name implies and nothing more

look into https://docs.github.com/en/actions/using-workflows/reusing-workflows for modularzation

**Comment by ghzlatarev** [comment]
More ideas: 
https://github.com/Manta-Network/Manta/pull/681#pullrequestreview-1040662163

**Comment by ghzlatarev** [comment]
https://github.com/Manta-Network/Manta/pull/781#discussion_r961006897
