### ISSUE TITLE
Metrics are not showing collated blocks

### ISSUE THREAD

**Issue by Suleymann85** [Manta-Network/Manta#612]
Metrics are not showing collated blocks while we are active collators.

When we do `curl localhost:9615/metrics | grep "substrate_proposer_block_constructed"`

the results is:

`substrate_proposer_block_constructed_count{chain="calamari"} 0`

**Comment by Garandor** [comment]
Hi, thanks for reporting this!

I found reference of others encountering and solving a similar issue here: https://github.com/integritee-network/parachain/issues/74

We will investigate if their situation also applies to us

**Comment by Garandor** [comment]
#582 will fix this
FYI @grenade
