### ISSUE TITLE
Get rid of all `unwrap` s in Manta Runtime Node.

### ISSUE THREAD

**Issue by stechu** [Manta-Network/Manta#63]
also include `pallet-manta-pay`

**Comment by ghzlatarev** [comment]
> also include `pallet-manta-pay`

There's an issue for pallet-manta-pay as well = https://github.com/Manta-Network/pallet-manta-pay/issues/44

**Comment by ghzlatarev** [comment]
Hmm this seems like a non-issue. I don't see any bad unwraps() in the manta runtime code.
Neither manta or manta-pc branches.
