### ISSUE TITLE
manta chainspec is incompatible with manta binary

### ISSUE THREAD

**Issue by grenade** [Manta-Network/Manta#667]
manta binaries subsequent to v3.1.1 are incompatible with the manta genesis chainspec (at https://github.com/Manta-Network/Manta/blob/manta/genesis/manta-genesis.json).
if one attempts to start a manta node (eg: `manta --chain manta ...`) with versions of manta greater than v3.1.1, the following error is shown in the manta log:
```
Error: Service(Application("Failed to parse `0x86aa36a140dfc449c30dbce16ce0fea33d5c3786766baa764e33f336841b9e29` as block number for code substitutes. In an old version the key for code substitute was a block hash. Please update the chain spec to a version that is compatible with your node."))
```

**Comment by ghzlatarev** [comment]
Manta genesis is regenerated, so this issue is no longer relevant
