### ISSUE TITLE
Shell Parachain (similar to Statemine)

### ISSUE THREAD

**Issue by stechu** [Manta-Network/Manta#67]

**Comment by Dengjianping** [comment]
- [x] clippy && fmt check
- [x] simplify manta-pc primitives
- [x] configure manta-pc genesus
- [x] might reorgganize the manta-pc project
- [x] renaming stuff
- [x] CI/CD
- [ ] ~~Readme update~~
- [ ] ~~docker build?~~

The last two tasks, we can update them later.
