### ISSUE TITLE
Move non-manta binary location to a config file for CI

### ISSUE THREAD

**Issue by Dengjianping** [Manta-Network/Manta#670]
Move like both binary locations to a yml, jsonor toml file, unnecessary to hardcode them in workflow file.

https://github.com/Manta-Network/Manta/blob/manta/.github/workflows/publish_draft_releases.yml#L191
https://github.com/Manta-Network/Manta/blob/manta/.github/workflows/publish_draft_releases.yml#L387

**Comment by Garandor** [comment]
And in the next step we can automate replacing this (and other chore tasks like creating the Changelog after #661) with a little shell script or rust tool

**Comment by Garandor** [comment]
has been done in the meantime, they're env variables now, still duplicated but good enough
