### ISSUE TITLE
Check total weight at session change boundary with staking enabled

### ISSUE THREAD

**Issue by Garandor** [Manta-Network/Manta#734]
Total weight of all calls at session change must be checked to ensure we're far away from the total block weight

- rotate_session
- reset_collator_performance
- staking set change
- first collator payout

Followup to https://github.com/Manta-Network/Manta/pull/720#discussion_r935014954

**Comment by ghzlatarev** [comment]
Consider resetting collator performance over several blocks if needed. We can store the cursor in a storage item and check it in the `on_initialize` hook of collator_selection.
pallet_session's `on_init `hook gets called first and that can set the cursor, then collator_selection's `on_init` can continue using in the same block and in the next.

**Comment by Garandor** [comment]
Since #691 we are using the `pallet_parachain_staking::Round` mechanism to recompute eligible authors.
This one has a proper weight measuring mechanism instead of the `full_block` assumption from pallet_session.
pallet_session's session rotation hooks have since been disabled

Closing this as no longer needed.
