### ISSUE TITLE
Automate Weight Comparison previous->current release

### ISSUE THREAD

**Issue by Garandor** [Manta-Network/Manta#807]
We are currently comparing weight files manually on each release.

Write a small tool that can
- read a weights file
- execute each of the `fn`s contained to obtain their weight output
- compare these with the weight outputs from a second weight file

Fail if any of the detected Weights differ by more than some significance barrier, e.g. 30% to alert a dev to check these manually or there are weights missing from one of the two files

**Comment by Dengjianping** [comment]
Run rust code like a script: https://github.com/fornwall/rust-script
