### ISSUE TITLE
Nimbus Branch Structure

### ISSUE THREAD

**Issue by stechu** [Manta-Network/Manta#825]
We would like to have a more reasonable nimbus branch structure on manta's nimbus fork and eventually upstream changes.

**Comment by Garandor** [comment]
New branch structure:

- upstreamable: branched off from main, containing changes we can eventually upstream
- manta: manta-specific changes that we likely won't upstream

the v4.0.0 tag and all future tags manta repo will use always point to the manta branch, which will get changes from main merged in periodically.
