### ISSUE TITLE
dev mode with instant-seal or without it

### ISSUE THREAD

**Issue by zqhxuyuan** [Manta-Network/Manta#828]
dev mode is usefull for local development. 
- [ ] the spec name to be used is open to discussion, maybe all spec ends_with `dev`?
- [ ] also support instant sealing mode.

**Comment by Garandor** [comment]
Nimbus technically supports it, i think moonbeam use it, i removed it from our node when porting Nimbus because our normal MO is `polkadot-launch`.

Could you elaborate what we would gain by readding it? It shouldn't be too difficult to do
