### ISSUE TITLE
Changelog Verification improvements

### ISSUE THREAD

**Issue by Garandor** [Manta-Network/Manta#843]
- [ ] Output the diff that failed on the action if changelog verification fails like here https://github.com/Manta-Network/Manta/actions/runs/3238041688/jobs/5305806288
- [ ] Use the PR title for the changelog entry, not the name of the merge commit ( on single commit PRs this uses the commit message of the single commit instead of the PR title ) or fails completely, like here https://github.com/Manta-Network/Manta/pull/833 where the PR was not added to the v3.4.2 changelog

**Comment by Apokalip** [comment]
> 
@Garandor 

Just to ask about the second one, you mean always use the PR title? If not what about the "Merge #123" cases

**Comment by Garandor** [comment]
> Just to ask about the second one, you mean always use the PR title? If not what about the "Merge #123" cases

Yeah, we're enforcing merges to manta to come from PRs so you can just always use the associated title for the changelog entry
