### ISSUE TITLE
Flip order of pallets in construct runtime

### ISSUE THREAD

**Issue by ferrell-code** [Manta-Network/Manta#859]
https://github.com/Manta-Network/Manta/blob/affbaccef75e68e990084c1a188ad52215fe0005/runtime/calamari/src/lib.rs#L806-L811

Reverse the order of these four pallets in `construct_runtime!`

Long term it may be good to fix https://github.com/Manta-Network/Manta/issues/378 as that is more intuitive

**Comment by ferrell-code** [comment]
This is most likely not important as we don't use pallet Session to rotate keys. I can't find any other reason why the hook order would be important, but good to keep in mind

**Comment by Garandor** [comment]
> This is most likely not important as we don't use pallet Session to rotate keys. I can't find any reason why the hook order is important, but good to keep in mind

Quick note: we *do* have a session-like rotation of `rounds` in `parachain-staking`, and rewards are paid at end-of-round similar to the relaychain. It's worth doublechecking hook order between `author-inherent` and `parachain_staking` is correct although even if it isn't the reward of the last author will just be delayed a round
