### ISSUE TITLE
issue with update v3.4.2

### ISSUE THREAD

**Issue by papadritta** [Manta-Network/Manta#874]
Hey Rob @grenade 

## when updating from v3.3.0 to v3.4.2 with apt package the update held by process #351825

```
Waiting for cache lock: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 351825 (aWaiting for cache lock: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 351825
```

**Comment by grenade** [comment]
https://www.google.com/search?q=Could+not+get+lock+%2Fvar%2Flib%2Fdpkg%2Flock-frontend

errors like this one are related to system configuration and the system package manager, not the individual package being installed. it is beyond the scope of this project to provide support in cases where a simple internet search will yield multiple resolution options.

**Comment by papadritta** [comment]
@grenade 
all sorted out
