### ISSUE TITLE
Add parameter sanity checks to `mantapay` public extrinsics

### ISSUE THREAD

**Issue by Garandor** [Manta-Network/Manta#880]
> Yes, to_private and to_public should add other kinds of checks like > 0 and < L for asset values

**Comment by Garandor** [comment]
could be implemented in the same effort as #878 
cc @zqhxuyuan

**Comment by zqhxuyuan** [comment]
`to_private` call can have `<L` check, but shouldn't have `>0` check, because some private_transfer is using to_private(sources:0) to mint zero coin. If we apply `>0` check on `to_private` call, then private_transfer may failed.

**Comment by zqhxuyuan** [comment]
`to_public` can have `>0` and `<L` check on sinks amount, do we really need it? Or If we need this, both `to_private` and `to_public` of `L` use same value, or different value? @Garandor

**Comment by Garandor** [comment]
> If we apply `>0` check on `to_private` call, then private_transfer may failed.

A private transfer should not be using `to_private`. It may use `post_transaction`, in which case you're right we need to allow the 0 sources case there, but I don't think a user manually creating a 0-value UTXO makes sense.

@bhgomes pls correct me if I'm wrong

> to_public can have >0 and <L check on sinks amount, do we really need it?

No, I don't think we want to limit any capital outflow from the system.
However, a `>0` check for `to_public` on the `sinks` field does make sense

**Comment by Garandor** [comment]
Lower limit check resolved with #948 
Upper limit left to followup issue #878
