### ISSUE TITLE
Use a more stable yamllint for CI

### ISSUE THREAD

**Issue by Dengjianping** [Manta-Network/Manta#923]
Just a recent update from `actionshub/yamllint@main` broke one of our CI job. So we better find a more stable alternative.

https://github.com/Manta-Network/Manta/actions/runs/3693066044/jobs/6253787124

**Comment by flame4** [comment]
However not every job fails with this new main branch, example: https://github.com/Manta-Network/Manta/actions/runs/3694615269/jobs/6256018229

Looks weird.

**Comment by flame4** [comment]
re-run the job and it works.  Seems some network error.
https://github.com/Manta-Network/Manta/actions/runs/3693066044
