### ISSUE TITLE
Trigger tx-pause freeze of chain state on `InternalLedgerError`

### ISSUE THREAD

**Issue by Garandor** [Manta-Network/Manta#951]
OK so if I get this correctly, the extrinsic will simply fail if we encounter an `InternalLedgerError`.

We need a followup topic to this:
Trigger tx-pause freeze of chain state on `InternalLedgerError`

_Originally posted by @Garandor in https://github.com/Manta-Network/Manta/pull/949#pullrequestreview-1231219623_

**Comment by Garandor** [comment]
Scoped to freezing private ledger only

**Comment by Garandor** [comment]
not sure this really is high priority, we can release for audit/mainnet without it if need be

**Comment by ghzlatarev** [comment]
> priority

Idk how I set it as high priority. It was just one of the issues from the release planning.

**Comment by Garandor** [comment]
If you pull it above another high-priority task it gets marked as high-prio.
The kanban is supposted to be sorted top->bottom by task priority

**Comment by ghzlatarev** [comment]
> If you pull it above another high-priority task it gets marked as high-prio. The kanban is supposted to be sorted top->bottom by task priority

Oh I didn't know about the automation. my bad.
