### ISSUE TITLE
Add pallet-scheduler into Manta-pc for parachain runtime upgrade

### ISSUE THREAD

**Issue by xialovexia** [Manta-Network/Manta#99]
`pallet-scheduler` allows the parachain to perform some operations after a specified number of blocks have been generated. For example, a runtime upgrade operation is performed after 10 blocks are generated. With `pallet-scheduler`, we can avoid such problems as block weight exhaust.

**Comment by Dengjianping** [comment]
I remember this issue has been implemented, right?
